[package]
name = "c64-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.10", features = ["derive", "cargo"] }
sdl2 = "0.35.2"
bytemuck = "1.14.0"
